/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_cubly_iopc_jni_MediaKeys */

#ifndef _Included_ru_cubly_iopc_jni_MediaKeys
#define _Included_ru_cubly_iopc_jni_MediaKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    volumeMute
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_volumeMute
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    volumeDown
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_volumeDown
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    volumeUp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_volumeUp
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    songPrevious
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_songPrevious
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    songNext
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_songNext
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    songPlayPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_songPlayPause
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_MediaKeys
 * Method:    mediaStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_MediaKeys_mediaStop
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
