/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ru_cubly_iopc_jni_VolumeControl */

#ifndef _Included_ru_cubly_iopc_jni_VolumeControl
#define _Included_ru_cubly_iopc_jni_VolumeControl
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ru_cubly_iopc_jni_VolumeControl
 * Method:    getMasterVolume
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_ru_cubly_iopc_jni_VolumeControl_getMasterVolume
  (JNIEnv *, jclass);

/*
 * Class:     ru_cubly_iopc_jni_VolumeControl
 * Method:    setMasterVolume
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_ru_cubly_iopc_jni_VolumeControl_setMasterVolume
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
